// Parity tests — load vectors.json (generated by reference/cmd/genvectors) and
// verify the Rust port produces byte-identical output for every case.
//
// To regenerate the vectors locally:
//   cd reference && go run ./cmd/genvectors ../tests/vectors.json

use serde_json::Value;

use kms_rs::crypto::aes::expand_key;
use kms_rs::crypto::kms_aes::{
    aes_decrypt_block_v4, aes_decrypt_block_v6, aes_encrypt_block_v4, aes_encrypt_block_v6,
    kms_decrypt_cbc, kms_encrypt_cbc, pkcs7_pad, pkcs7_unpad,
};
use kms_rs::crypto::v4_hash::v4_hash;
use kms_rs::crypto::v6_mac::{v6_hmac, v6_mac_key};
use kms_rs::kms::base::{
    server_logic, GenericRequestHeader, KmsRequest, KmsResponse, ServerConfig,
};
use kms_rs::kms::filetime::{filetime_to_unix, unix_to_filetime};
use kms_rs::kms::utf16::{decode_utf16le, encode_utf16le};
use kms_rs::kms::uuid::KmsUuid;
use kms_rs::kms::versions::handle_v4_request;
use kms_rs::rpc::{
    build_bind_ack_response, build_bind_request, build_msrpc_response, build_rpc_request,
    MsRpcRequestHeader,
};

const VECTORS_JSON_PATH: &str = "tests/vectors.json";

fn vectors() -> Value {
    let data = std::fs::read_to_string(VECTORS_JSON_PATH).unwrap_or_else(|e| {
        panic!(
            "failed to read {}: {} — generate it with `cd reference && go run ./cmd/genvectors ../tests/vectors.json`",
            VECTORS_JSON_PATH, e
        )
    });
    serde_json::from_str(&data).expect("invalid vectors.json")
}

fn hex_str(b: &[u8]) -> String {
    let mut s = String::with_capacity(b.len() * 2);
    for &x in b {
        s.push_str(&format!("{:02x}", x));
    }
    s
}

fn from_hex(s: &str) -> Vec<u8> {
    let bytes = s.as_bytes();
    assert!(bytes.len() % 2 == 0, "odd-length hex: {}", s);
    let mut out = Vec::with_capacity(bytes.len() / 2);
    let mut i = 0;
    while i < bytes.len() {
        let hi = hex_val(bytes[i]).expect("bad hex");
        let lo = hex_val(bytes[i + 1]).expect("bad hex");
        out.push((hi << 4) | lo);
        i += 2;
    }
    out
}

fn hex_val(c: u8) -> Option<u8> {
    match c {
        b'0'..=b'9' => Some(c - b'0'),
        b'a'..=b'f' => Some(c - b'a' + 10),
        b'A'..=b'F' => Some(c - b'A' + 10),
        _ => None,
    }
}

// ---------- helpers for case iteration ----------

fn arr<'a>(v: &'a Value, key: &str) -> &'a Vec<Value> {
    v.get(key)
        .unwrap_or_else(|| panic!("missing {}", key))
        .as_array()
        .unwrap_or_else(|| panic!("{} not an array", key))
}

fn s<'a>(v: &'a Value, k: &str) -> &'a str {
    v.get(k)
        .unwrap_or_else(|| panic!("missing field {}", k))
        .as_str()
        .unwrap_or_else(|| panic!("field {} not a string", k))
}

fn opt_s<'a>(v: &'a Value, k: &str) -> Option<&'a str> {
    v.get(k).and_then(|x| x.as_str())
}

fn b(v: &Value, k: &str) -> bool {
    v.get(k).and_then(|x| x.as_bool()).unwrap_or(false)
}

fn u(v: &Value, k: &str) -> u64 {
    v.get(k).and_then(|x| x.as_u64()).unwrap_or(0)
}

// ---------- Tests ----------

#[test]
fn parity_pkcs7_pad() {
    for case in arr(&vectors(), "pkcs7_pad") {
        let input = from_hex(s(case, "input"));
        let out = pkcs7_pad(&input, 16);
        assert_eq!(hex_str(&out), s(case, "out"));
    }
}

#[test]
fn parity_pkcs7_unpad() {
    for case in arr(&vectors(), "pkcs7_unpad") {
        let input = from_hex(s(case, "input"));
        let res = pkcs7_unpad(&input);
        if b(case, "ok") {
            let out = res.expect("expected ok");
            assert_eq!(hex_str(&out), s(case, "out"));
        } else {
            assert!(res.is_err(), "expected error for {}", s(case, "input"));
        }
    }
}

#[test]
fn parity_v4_block() {
    for case in arr(&vectors(), "v4_block") {
        let input = from_hex(s(case, "input"));
        let mut enc = [0u8; 16];
        aes_encrypt_block_v4(&input, &mut enc);
        assert_eq!(hex_str(&enc), s(case, "enc"));
        let mut dec = [0u8; 16];
        aes_decrypt_block_v4(&enc, &mut dec);
        assert_eq!(hex_str(&dec), s(case, "dec_of_enc"));
    }
}

#[test]
fn parity_v6_block() {
    for case in arr(&vectors(), "v6_block") {
        let input = from_hex(s(case, "input"));
        let mut enc = [0u8; 16];
        aes_encrypt_block_v6(&input, &mut enc);
        assert_eq!(hex_str(&enc), s(case, "enc"));
        let mut dec = [0u8; 16];
        aes_decrypt_block_v6(&enc, &mut dec);
        assert_eq!(hex_str(&dec), s(case, "dec_of_enc"));
    }
}

#[test]
fn parity_v5_cbc() {
    for case in arr(&vectors(), "v5_cbc") {
        let iv = from_hex(s(case, "iv"));
        let plain = from_hex(s(case, "plain"));
        let cipher = kms_encrypt_cbc(&plain, &iv, false).unwrap();
        assert_eq!(hex_str(&cipher), s(case, "cipher"));
        let dec = kms_decrypt_cbc(&cipher, &iv, false).unwrap();
        assert_eq!(hex_str(&dec), s(case, "decrypted"));
    }
}

#[test]
fn parity_v6_cbc() {
    for case in arr(&vectors(), "v6_cbc") {
        let iv = from_hex(s(case, "iv"));
        let plain = from_hex(s(case, "plain"));
        let cipher = kms_encrypt_cbc(&plain, &iv, true).unwrap();
        assert_eq!(hex_str(&cipher), s(case, "cipher"));
        let dec = kms_decrypt_cbc(&cipher, &iv, true).unwrap();
        assert_eq!(hex_str(&dec), s(case, "decrypted"));
    }
}

#[test]
fn parity_v4_hash() {
    for case in arr(&vectors(), "v4_hash") {
        let input = from_hex(s(case, "input"));
        let h = v4_hash(&input);
        assert_eq!(hex_str(&h), s(case, "hash"));
    }
}

#[test]
fn parity_v6_mac_key() {
    for case in arr(&vectors(), "v6_mac_key") {
        let t: u64 = s(case, "request_time").parse().unwrap();
        let k = v6_mac_key(t);
        assert_eq!(hex_str(&k), s(case, "key"));
    }
}

#[test]
fn parity_v6_hmac() {
    for case in arr(&vectors(), "v6_hmac") {
        let key = from_hex(s(case, "key"));
        let data = from_hex(s(case, "data"));
        let h = v6_hmac(&key, &data);
        assert_eq!(hex_str(&h), s(case, "hmac"));
    }
}

#[test]
fn parity_uuid_string() {
    for case in arr(&vectors(), "uuid_string") {
        let input = s(case, "input");
        let u = KmsUuid::parse(input).expect(input);
        assert_eq!(hex_str(u.as_bytes()), s(case, "bytes_le"));
        assert_eq!(u.to_string(), s(case, "string"));
    }
}

#[test]
fn parity_uuid_parse() {
    for case in arr(&vectors(), "uuid_parse") {
        let input = s(case, "input");
        let u = KmsUuid::parse(input).expect(input);
        assert_eq!(hex_str(u.as_bytes()), s(case, "bytes_le"));
    }
}

#[test]
fn parity_filetime() {
    for case in arr(&vectors(), "filetime") {
        let ft: i64 = s(case, "filetime").parse().unwrap();
        let want_secs: i64 = s(case, "secs").parse().unwrap();
        let want_nanos: u64 = u(case, "nanos");
        let (secs, nanos) = filetime_to_unix(ft);
        assert_eq!(secs, want_secs, "secs mismatch for ft {}", ft);
        assert_eq!(nanos as u64, want_nanos, "nanos mismatch for ft {}", ft);
        let roundtrip: i64 = s(case, "roundtrip").parse().unwrap();
        assert_eq!(unix_to_filetime(secs, nanos), roundtrip);
    }
}

#[test]
fn parity_utf16le() {
    for case in arr(&vectors(), "utf16le") {
        let input = s(case, "input");
        let enc = encode_utf16le(input);
        assert_eq!(hex_str(&enc), s(case, "utf16le"));
        // Append two null bytes (mirrors Go's test) and decode.
        let mut padded = from_hex(s(case, "utf16le"));
        padded.push(0);
        padded.push(0);
        let decoded = decode_utf16le(&padded);
        assert_eq!(decoded, s(case, "decoded"));
    }
}

#[test]
fn parity_kms_request_marshal_parse() {
    for case in arr(&vectors(), "kms_request") {
        let wire = from_hex(s(case, "wire"));
        let parsed = KmsRequest::parse(&wire).unwrap();
        let rt = parsed.marshal();
        assert_eq!(hex_str(&rt), s(case, "roundtrip"));
    }
}

#[test]
fn parity_kms_response_marshal_parse() {
    for case in arr(&vectors(), "kms_response") {
        let wire = from_hex(s(case, "wire"));
        let parsed = KmsResponse::parse(&wire).unwrap();
        let rt = parsed.marshal();
        assert_eq!(hex_str(&rt), s(case, "roundtrip"));
        assert_eq!(parsed.epid_len as u64, u(case, "epid_len"));
    }
}

#[test]
fn parity_generic_header() {
    for case in arr(&vectors(), "generic_hdr") {
        let input = from_hex(s(case, "input"));
        let h = GenericRequestHeader::parse(&input).unwrap();
        assert_eq!(h.body_length1 as u64, u(case, "body_length1"));
        assert_eq!(h.body_length2 as u64, u(case, "body_length2"));
        assert_eq!(h.version_minor as u64, u(case, "version_minor"));
        assert_eq!(h.version_major as u64, u(case, "version_major"));
    }
}

#[test]
fn parity_rpc_bind_request() {
    for case in arr(&vectors(), "rpc_bind_req") {
        let cid = u(case, "call_id") as u32;
        let bytes = build_bind_request(cid);
        assert_eq!(hex_str(&bytes), s(case, "bytes"));
    }
}

#[test]
fn parity_rpc_bind_ack() {
    for case in arr(&vectors(), "rpc_bind_ack") {
        let request = from_hex(s(case, "request"));
        let port = u(case, "port") as u16;
        let call_id = u(case, "call_id") as u32;
        let bytes = build_bind_ack_response(&request, port, call_id).unwrap();
        assert_eq!(hex_str(&bytes), s(case, "bytes"));
    }
}

#[test]
fn parity_rpc_request() {
    for case in arr(&vectors(), "rpc_request") {
        let data = from_hex(s(case, "kms_data"));
        let cid = u(case, "call_id") as u32;
        let bytes = build_rpc_request(&data, cid);
        assert_eq!(hex_str(&bytes), s(case, "bytes"));
    }
}

#[test]
fn parity_rpc_response() {
    for case in arr(&vectors(), "rpc_response") {
        let req_header_bytes = from_hex(s(case, "req_header_bytes"));
        let h = MsRpcRequestHeader::parse(&req_header_bytes).unwrap();
        let pdu = from_hex(s(case, "pdu"));
        let bytes = build_msrpc_response(&h, &pdu);
        assert_eq!(hex_str(&bytes), s(case, "bytes"));
    }
}

#[test]
fn parity_handle_v4() {
    for case in arr(&vectors(), "handle_v4") {
        let request = from_hex(s(case, "request"));
        let mut cfg = ServerConfig::default();
        cfg.epid = "03612-00206-471-111111-03-1033-19041.0000-1232024".into();
        let resp = handle_v4_request(&request, &cfg).unwrap();
        assert_eq!(hex_str(&resp), s(case, "response"));
    }
}

#[test]
fn parity_server_logic() {
    let vectors = vectors();
    let cases = arr(&vectors, "server_logic");
    // First case: full request + response wire.
    let first = &cases[0];
    let req = KmsRequest::parse(&from_hex(s(first, "request"))).unwrap();
    let mut cfg = ServerConfig::default();
    cfg.epid = "03612-00206-471-111111-03-1033-19041.0000-1232024".into();
    cfg.activation = 120;
    cfg.renewal = 10080;
    let resp = server_logic(&req, &cfg);
    assert_eq!(hex_str(&resp.marshal()), s(first, "response_wire"));
    assert_eq!(hex_str(&resp.kms_epid), s(first, "epid_utf16le"));
    assert_eq!(resp.current_client_count as u64, u(first, "current_client_count"));

    // Subsequent cases: client_count -> expected current_client_count.
    for case in &cases[1..] {
        let cc = u(case, "client_count") as u32;
        let expected = u(case, "current_client_count") as u32;
        let mut cfg2 = ServerConfig::default();
        cfg2.epid = "fixed-epid".into();
        cfg2.client_count = if cc > 0 { Some(cc) } else { Some(0) };
        // Match Go behaviour: cc == 0 yields 0 (since none of the conditions hit).
        let resp = server_logic(&req, &cfg2);
        assert_eq!(resp.current_client_count, expected, "client_count={}", cc);
    }
}

#[test]
fn parity_v5_envelope() {
    parity_v5_v6_envelope("v5_envelope", false);
}

#[test]
fn parity_v6_envelope() {
    parity_v5_v6_envelope("v6_envelope", true);
}

fn parity_v5_v6_envelope(key: &str, is_v6: bool) {
    use kms_rs::crypto::v6_mac::v6_hmac_parts;
    use kms_rs::kms::base::get_padding;
    use sha2::{Digest, Sha256};

    for case in arr(&vectors(), key) {
        let req_bytes = from_hex(s(case, "request_bytes"));
        let salt = from_hex(s(case, "salt"));
        let decrypted_salt = from_hex(s(case, "decrypted_salt"));
        let random_salt = from_hex(s(case, "random_salt"));
        let salt_s = from_hex(s(case, "salt_s"));
        let epid_utf16le = from_hex(s(case, "epid_utf16le"));
        let hwid = from_hex(s(case, "hwid"));
        let want_response_bytes = from_hex(s(case, "response_bytes"));
        let want_encrypted = from_hex(s(case, "encrypted"));
        let want_full = from_hex(s(case, "full"));

        let req = KmsRequest::parse(&req_bytes).unwrap();
        let mut cfg = ServerConfig::default();
        cfg.hwid = hwid.clone();
        cfg.set_epid_bytes(epid_utf16le.clone());
        let resp = server_logic(&req, &cfg);
        let response_bytes = resp.marshal();
        assert_eq!(response_bytes, want_response_bytes, "response_bytes mismatch");

        let hash_result = Sha256::digest(&random_salt);

        let (encrypted, iv): (Vec<u8>, Vec<u8>) = if is_v6 {
            let mut msg = Vec::with_capacity(response_bytes.len() + 16 + 32 + cfg.hwid.len() + 16 + 16);
            msg.extend_from_slice(&response_bytes);
            for i in 0..16 {
                msg.push(salt[i] ^ decrypted_salt[i] ^ random_salt[i]);
            }
            msg.extend_from_slice(&hash_result);
            msg.extend_from_slice(&cfg.hwid);
            for i in 0..16 {
                msg.push(salt[i] ^ decrypted_salt[i]);
            }
            let dsalt_s = kms_decrypt_cbc(&salt_s, &salt_s, true).unwrap();
            let hmac_key = v6_mac_key(req.request_time);
            let mut xor_salts = [0u8; 16];
            for i in 0..16 {
                xor_salts[i] = salt_s[i] ^ dsalt_s[i];
            }
            let digest = v6_hmac_parts(&hmac_key, &[&xor_salts, &msg]);
            msg.extend_from_slice(&digest[16..]);
            let padded = pkcs7_pad(&msg, 16);
            let enc = kms_encrypt_cbc(&padded, &salt_s, true).unwrap();
            (enc, salt_s.clone())
        } else {
            let mut rd = Vec::with_capacity(response_bytes.len() + 16 + 32);
            rd.extend_from_slice(&response_bytes);
            for i in 0..16 {
                rd.push(decrypted_salt[i] ^ salt[i] ^ random_salt[i]);
            }
            rd.extend_from_slice(&hash_result);
            let padded = pkcs7_pad(&rd, 16);
            let enc = kms_encrypt_cbc(&padded, &salt, false).unwrap();
            (enc, salt.clone())
        };

        assert_eq!(encrypted, want_encrypted, "encrypted mismatch");

        let body_length = (2 + 2 + iv.len() + encrypted.len()) as u32;
        let padding = vec![0u8; get_padding(body_length as usize)];
        let mut full = Vec::with_capacity(4 + 4 + 4 + 2 + 2 + iv.len() + encrypted.len() + padding.len());
        full.extend_from_slice(&body_length.to_le_bytes());
        full.extend_from_slice(&0x00000200u32.to_be_bytes());
        full.extend_from_slice(&body_length.to_le_bytes());
        full.extend_from_slice(&req.version_minor.to_le_bytes());
        full.extend_from_slice(&req.version_major.to_le_bytes());
        full.extend_from_slice(&iv);
        full.extend_from_slice(&encrypted);
        full.extend_from_slice(&padding);
        assert_eq!(full, want_full, "full wire mismatch");
    }
}

#[test]
fn parity_constants() {
    let v = vectors();
    let c = &v["constants"];
    assert_eq!(u(c, "msrpc_header_size"), kms_rs::rpc::MSRPC_HEADER_SIZE as u64);
    assert_eq!(
        u(c, "msrpc_request_header_size"),
        kms_rs::rpc::MSRPC_REQUEST_HEADER_SIZE as u64
    );
    assert_eq!(
        u(c, "msrpc_resp_header_size"),
        kms_rs::rpc::MSRPC_RESP_HEADER_SIZE as u64
    );
    assert_eq!(u(c, "ctx_item_size"), kms_rs::rpc::CTX_ITEM_SIZE as u64);
    assert_eq!(
        u(c, "ctx_item_result_size"),
        kms_rs::rpc::CTX_ITEM_RESULT_SIZE as u64
    );
}

// Keep a reference to `expand_key` to suppress unused-import warnings.
#[test]
fn ensure_expand_key_linked() {
    let k = expand_key(&[0u8; 16], 16, 176);
    assert_eq!(k.len(), 176);
}
